ARG ARCHTAG
FROM openwebrx-base:$ARCHTAG

ADD docker/scripts/install-dependencies-rtlsdr.sh /
ADD docker/scripts/install-connectors.sh /

RUN /install-dependencies-rtlsdr.sh &&\
    rm /install-dependencies-rtlsdr.sh &&\
    /install-connectors.sh &&\
    rm /install-connectors.sh

ADD . /opt/openwebrx
