ARG ARCHTAG
FROM openwebrx-soapysdr-base:$ARCHTAG

ADD docker/scripts/install-dependencies-limesdr.sh /
RUN /install-dependencies-limesdr.sh
RUN rm /install-dependencies-limesdr.sh

ADD docker/scripts/install-connectors.sh /
RUN /install-connectors.sh
RUN rm /install-connectors.sh
