ARG ARCHTAG
FROM openwebrx-soapysdr-base:$ARCHTAG

COPY docker/scripts/install-dependencies-soapyremote.sh /
RUN /install-dependencies-soapyremote.sh &&\
    rm /install-dependencies-soapyremote.sh

COPY . /opt/openwebrx
