ARG ARCHTAG
FROM openwebrx-base:$ARCHTAG

ADD docker/scripts/install-dependencies-*.sh /
ADD docker/files/sdrplay/install-lib.*.patch /

RUN /install-dependencies-rtlsdr.sh &&\
    /install-dependencies-soapysdr.sh &&\
    /install-dependencies-hackrf.sh &&\
    /install-dependencies-sdrplay.sh &&\
    /install-dependencies-airspy.sh &&\
    /install-dependencies-rtlsdr-soapy.sh &&\
    /install-dependencies-plutosdr.sh &&\
    /install-dependencies-limesdr.sh &&\
    /install-dependencies-soapyremote.sh &&\
    /install-dependencies-perseus.sh &&\
    rm /install-dependencies-*.sh &&\
    rm /install-lib.*.patch

ADD docker/scripts/install-connectors.sh /
RUN /install-connectors.sh &&\
    rm /install-connectors.sh

ADD docker/files/services/sdrplay /etc/services.d/sdrplay

ADD . /opt/openwebrx
