ARG ARCHTAG
FROM openwebrx-soapysdr-base:$ARCHTAG

COPY docker/scripts/install-dependencies-redpitaya.sh /
RUN /install-dependencies-redpitaya.sh &&\
    rm /install-dependencies-redpitaya.sh

COPY . /opt/openwebrx
