ARG ARCH
FROM openwebrx-base:$ARCH

ADD docker/scripts/install-dependencies-*.sh /
ADD docker/scripts/install-lib.*.patch /

RUN /install-dependencies-rtlsdr.sh
RUN /install-dependencies-hackrf.sh
RUN /install-dependencies-soapysdr.sh
RUN /install-dependencies-sdrplay.sh
RUN /install-dependencies-airspy.sh
