FROM debian:buster-slim

ADD docker/scripts/js8call-hamlib.patch /
ADD docker/scripts/install-dependencies.sh /
RUN /install-dependencies.sh && \
    rm /install-dependencies.sh

WORKDIR /opt/openwebrx

VOLUME /etc/openwebrx

ENTRYPOINT [ "/opt/openwebrx/docker/scripts/run.sh" ]
EXPOSE 8073
