ARG ARCHTAG
FROM openwebrx-soapysdr-base:$ARCHTAG

COPY docker/scripts/install-dependencies-hackrf.sh /
RUN /install-dependencies-hackrf.sh &&\
    rm /install-dependencies-hackrf.sh

COPY . /opt/openwebrx
