ARG ARCHTAG
FROM openwebrx-soapysdr-base:$ARCHTAG

COPY docker/scripts/install-dependencies-afedri.sh /
RUN /install-dependencies-afedri.sh &&\
    rm /install-dependencies-afedri.sh

ADD . /opt/openwebrx
