ARG ARCHTAG
FROM openwebrx-base:$ARCHTAG

COPY docker/scripts/install-dependencies-soapysdr.sh \
     docker/scripts/install-connectors.sh /
RUN /install-dependencies-soapysdr.sh &&\
    rm /install-dependencies-soapysdr.sh &&\
    /install-connectors.sh &&\
    rm /install-connectors.sh
