ARG ARCHTAG
FROM openwebrx-base:$ARCHTAG

COPY docker/scripts/install-dependencies-*.sh \
     docker/files/sdrplay/install-lib.*.patch \
     docker/scripts/install-connectors.sh /

RUN /install-dependencies-rtlsdr.sh &&\
    /install-dependencies-soapysdr.sh &&\
    /install-dependencies-hackrf.sh &&\
    /install-dependencies-sdrplay.sh &&\
    /install-dependencies-airspy.sh &&\
    /install-dependencies-afedri.sh &&\
    /install-dependencies-rtlsdr-soapy.sh &&\
    /install-dependencies-plutosdr.sh &&\
    /install-dependencies-limesdr.sh &&\
    /install-dependencies-soapyremote.sh &&\
    /install-dependencies-perseus.sh &&\
    /install-dependencies-fcdpp.sh &&\
    /install-dependencies-radioberry.sh &&\
    /install-dependencies-uhd.sh &&\
    /install-dependencies-hpsdr.sh &&\
    /install-dependencies-bladerf.sh &&\
    /install-connectors.sh &&\
    /install-dependencies-runds.sh &&\
    rm /install-dependencies-*.sh &&\
    rm /install-lib.*.patch && \
    rm /install-connectors.sh

COPY docker/files/services/sdrplay /etc/services.d/sdrplay

ADD . /opt/openwebrx
