FROM debian:buster

RUN apt-get update && \
    apt-get install -y cmake build-essential devscripts debsigs dh-python python3 python3-setuptools dh-systemd git && \
    rm -rf /var/lib/apt/lists/*

ADD docker/scripts/build-debian-package.sh /

RUN git clone https://github.com/jketterl/openwebrx.git /openwebrx

WORKDIR /openwebrx

CMD ["/build-debian-package.sh"]
