ARG ARCHTAG
FROM openwebrx-base:$ARCHTAG

COPY docker/scripts/install-dependencies-rtlsdr.sh \
     docker/scripts/install-connectors.sh /

RUN /install-dependencies-rtlsdr.sh &&\
    rm /install-dependencies-rtlsdr.sh &&\
    /install-connectors.sh &&\
    rm /install-connectors.sh

COPY . /opt/openwebrx
