ARG ARCHTAG
FROM openwebrx-soapysdr-base:$ARCHTAG

ADD docker/scripts/install-dependencies-airspy.sh /
RUN /install-dependencies-airspy.sh &&\
    rm /install-dependencies-airspy.sh

ADD . /opt/openwebrx
