ARG ARCHTAG
FROM openwebrx-soapysdr-base:$ARCHTAG

ADD docker/scripts/install-dependencies-sdrplay.sh /
ADD docker/scripts/install-lib.*.patch /
RUN /install-dependencies-sdrplay.sh &&\
    rm /install-dependencies-sdrplay.sh &&\
    rm /install-lib.*.patch
