ARG ARCHTAG
FROM openwebrx-soapysdr-base:$ARCHTAG

ADD docker/scripts/install-dependencies-airspy.sh /
RUN /install-dependencies-airspy.sh

ADD docker/scripts/install-connectors.sh /
RUN /install-connectors.sh
