$(function(){
    $('.map-input').mapInput();
    $('.imageupload').imageUpload();
    $('.bookmarks').bookmarktable();
    $('.wsjt-decoding-depths').wsjtDecodingDepthsInput();
    $('#waterfall_scheme').waterfallDropdown();
    $('#rf_gain').gainInput();
    $('.optional-section').optionalSection();
    $('#scheduler').schedulerInput();
    $('.exponential-input').exponentialInput();
    $('.device-log-messages').logMessages();
});